#kubectl apply -f aws-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: my-aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQVNZWkYzQjJVN0JZRldZQTQ=
  AWS_SECRET_ACCESS_KEY: SGlIWUlhbHZzVHlJNzlCdTZoVWoxTEMwYVNnVTEzc2JUTmpya3pBdw==