apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: udagram-api-feed
        image: linhtinh603/udagram-api-feed
        envFrom:
        - configMapRef:
            name: my-env-configmap
        - secretRef:
            name: my-env-secret
        - secretRef:
            name: my-aws-secret
        ports:
        - containerPort: 8080
        resources:
         requests:
          cpu: "500m"

